title: Bruno's website
description: A blog about science, society, the universe and all that's in it, in english and in french
remote_theme: mmistakes/minimal-mistakes-jekyll

# Pour un blog
show_excerpts: true
